#!/usr/bin/env bash

# Update package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Backup original configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Write new HAProxy configuration
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
global
	log /dev/log    local0
	log /dev/log    local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 521318-web-01 100.25.2.29:80 check
	server 521318-web-02 3.83.238.232:80 check

# Enable HAProxy stats page
listen stats
	bind *:8080
	stats enable
	stats uri /stats
	stats auth admin:password
EOF'

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Print status
sudo systemctl status haproxy

