#!/usr/bin/env bash
# A script that does the Fizzbuzz challenge

num=1

while [ "$num" -le 100 ]; do


  if ! (( num % 3 )) && ! (( num % 5 )); then
    echo "FizzBuzz"
  elif ! (( num % 3 )); then
    echo "Fizz"
  elif ! (( num % 5 )); then
    echo "Buzz"
  else
    echo "$num"
  fi
  
  ((num++))
done
