#!/usr/bin/env bash
# Prints bad luck for the 4th interation, good luck for the 8th and Best School for the rest

i=1

while [ "$i" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    iecho "Best School"
  fi

  ((i++))
done
