#!/usr/bin/env bash
# Prints the numbers from 0 to 20 except for some special cases where it prints a message

i=1

while [ "$i" -lt 21 ]; do
  
  case "$i" in
    4)
      echo "$i"
      echo "bad luck from China"
      ;;
    9)
      echo "$i"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$i"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac

  ((i++))
done
